### ISSUE TITLE
how to print function caller stack?

### ISSUE THREAD

**Issue by romberli** [uber-go/zap#1046] opened 2022-01-05 08:42 UTC
here is the test code.
```
package main

import (
	"errors"
	"fmt"
	"os"

	"go.uber.org/zap"
)

func funcA() error {
	return errors.New("function error")
}

func funcB() error {
	return funcA()
}

func funcC() error {
	return funcB()
}

func main() {
	logger, err := zap.NewProduction()
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}

	err = funcC()
	logger.Error(err.Error())
}
```
output:
```
{
    "level": "error",
    "ts": 1641371801.0257752,
    "caller": "main/main.go:31",
    "msg": "function error",
    "stacktrace": "main.main\n\t/Users/romber/work/source_code/go/src/github.com/romberli/golang-test/test06/main/main.go:31\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225"
}
```
you can see that there is no information about funcA, funcB and funcC in the stacktrace. when the calling chain is deep, it's hard to find out which one is the original function that returns the error,
I hope that the stacktrace could print funcA, funcB and funcC to help me locate original function that returns the error.
did I miss something?

**Comment by abhinav** [comment] 2022-01-05 16:41
Hello. No information is reported about where the error comes from because no such information is available or tracked. Go does not augment errors with a stack trace of where they came from, so Zap cannot log it.

In Go, you'd typically [wrap the error](https://github.com/uber-go/guide/blob/master/style.md#error-wrapping), adding information to it to help you find the root cause. For example, in funcB you might do:

```go
func funcB() error {
  if err := funcA(); err != nil {
    return fmt.Errorf("a: %w", err)
  }

  // ...
  return nil
}
```

(This is obviously an unrealistic example, but the general principle applies.)

Following that, Zap will log the final message error message—whatever it may be.

Optionally, instead of `fmt.Errorf` with `%w`, you can also use third-party libraries like [pkg/errors](https://pkg.go.dev/github.com/pkg/errors) that provide a convenient mean of wrapping such errors:

```go
import "github.com/pkg/errors"

func funcB() error {
  return errors.Wrap(funcA(), "a") // returns nil if funcA returns nil
}
```

If you use pkg/errors, you can also use [its variant of errors.New](https://pkg.go.dev/github.com/pkg/errors#New) which records a stack trace at the call site. That's just a drop-in:

```diff
-import "errors"
+import "github.com/pkg/errors"

 func funcA() error {
 	return errors.New("function error")
 }
```

Zap will log that if available—but based on the usage above, that won't be enough.
The code above is using `logger.Error(err.Error())`. The signature of [`logger.Error`](https://pkg.go.dev/go.uber.org/zap#Logger.Error) is:

    func (log *Logger) Error(msg string, fields ...Field)

The first argument is a string message, not the error.
So when you do `log.Error(err.Error())`, from Zap's point of view,
the code above is just passing in an arbitrary string—there's no error to inspect or extract a stack trace from.

The string passed to Error should be a meaningful user-facing message,
and the error should be passed in via [zap.Error(err)](https://pkg.go.dev/go.uber.org/zap#Error).

[Here's a verison](https://go.dev/play/p/piwq0TGvTZs) of the above that uses pkg/errors, and passes the error in via `zap.Error`. The stack trace captuerd by pkg/errors is available in the `errorVerbose` field:

```
"errorVerbose":"function error\nmain.funcA\n\t/tmp/sandbox657452097/prog.go:12\nmain.funcB\n\t/tmp/sandbox657452097/prog.go:16\nmain.funcC\n\t/tmp/sandbox657452097/prog.go:20\nmain.main\n\t/tmp/sandbox657452097/prog.go:30\nruntime.main\n\t/usr/local/go-faketime/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go-faketime/src/runtime/asm_amd64.s:1581"
```

In a more readable form:

```
function error
main.funcA
	/tmp/sandbox657452097/prog.go:12
main.funcB
	/tmp/sandbox657452097/prog.go:16
main.funcC
	/tmp/sandbox657452097/prog.go:20
main.main
	/tmp/sandbox657452097/prog.go:30
runtime.main
	/usr/local/go-faketime/src/runtime/proc.go:255
runtime.goexit
	/usr/local/go-faketime/src/runtime/asm_amd64.s:1581
```

---

Closing because answered. Feel free to re-open or create another issue if you have more questions.
Thanks!

**Closed by abhinav** 2022-01-05 16:41 UTC
Labels: question

**Comment by romberli** [comment] 2022-01-06 09:18
thank you so much, that's very clear
