### ISSUE TITLE
Can console encoder allow using space instead of tab as seperator?

### ISSUE THREAD

**Issue by susanhuhu** [uber-go/zap#825] opened 2020-04-30 03:46 UTC
Currently among fields, console encoder adds tab and this is hard coded.  This makes log format urgly in OMS.  Can we allow changing this?  Actually it'll be really helpful if zap logger can add support for LogFormatter that allows customize the whole log message, instead of only allowing customizing each field.

**Comment by prashantv** [comment] 2020-04-30 04:08
This isn't possible today, but there is another similar feature request, see #814 and the pending change #697.

I think having a fully customizable encoder is a good idea, but zap makes it easy to implement this outside of zap, so we're not planning to add something like that directly in zap.

Closing as duplicate of #814.

**Closed by prashantv** 2020-04-30 04:08 UTC
