### ISSUE TITLE
How to overwrite fields in sub-loggers?

### ISSUE THREAD

**Issue by WarSys** [uber-go/zap#822] opened 2020-04-27 15:55 UTC
Code:

```go
func multipleSublogs() {
	root, _ := zap.Config{
		Level:    zap.NewAtomicLevelAt(zap.DebugLevel),
		Encoding: "console",
		Sampling: &zap.SamplingConfig{
			Initial:    5,
			Thereafter: 5,
		},
		EncoderConfig: zapcore.EncoderConfig{
			TimeKey:        "time",
			LevelKey:       "level",
			NameKey:        "logger",
			CallerKey:      "caller",
			MessageKey:     "msg",
			StacktraceKey:  "stacktrace",
			LineEnding:     zapcore.DefaultLineEnding,
			EncodeLevel:    zapcore.CapitalColorLevelEncoder,
			EncodeTime:     zapcore.ISO8601TimeEncoder,
			EncodeDuration: zapcore.StringDurationEncoder,
			EncodeCaller:   zapcore.ShortCallerEncoder,
		},
		DisableStacktrace: true,
		OutputPaths:       []string{"stderr"},
		ErrorOutputPaths:  []string{"stderr"},
	}.Build()
	defer root.Sync()

	logger := root.With(zap.String("root", "1st"))
	logger.Debug("#1 This is a DEBUG message")
	logger.Info("#1 This is an INFO message")
	logger.Warn("#1 This is a WARN message")
	logger.Error("#1 This is an ERROR message")
	logger.DPanic("#1 This is a DPANIC message")

	logger = logger.With(zap.String("root", "2nd")).WithOptions(zap.IncreaseLevel(zap.InfoLevel))
	logger.Debug("#2 This is a DEBUG message")
	logger.Info("#2 This is an INFO message")
	logger.Warn("#2 This is a WARN message")
	logger.Error("#2 This is an ERROR message")
	logger.DPanic("#2 This is a DPANIC message")

	logger = logger.With(zap.String("root", "3rd")).WithOptions(zap.IncreaseLevel(zap.ErrorLevel))
	logger.Debug("#3 This is a DEBUG message")
	logger.Info("#3 This is an INFO message")
	logger.Warn("#3 This is a WARN message")
	logger.Error("#3 This is an ERROR message")
	logger.DPanic("#3 This is a DPANIC message")
}
```

Actual:
```log
2020-04-27T23:54:29.065+0800	DEBUG	logsys/learn_more.go:182	#1 This is a DEBUG message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	INFO	logsys/learn_more.go:183	#1 This is an INFO message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	WARN	logsys/learn_more.go:184	#1 This is a WARN message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	ERROR	logsys/learn_more.go:185	#1 This is an ERROR message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	DPANIC	logsys/learn_more.go:186	#1 This is a DPANIC message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	INFO	logsys/learn_more.go:190	#2 This is an INFO message	{"root": "1st", "root": "2nd"}
2020-04-27T23:54:29.065+0800	WARN	logsys/learn_more.go:191	#2 This is a WARN message	{"root": "1st", "root": "2nd"}
2020-04-27T23:54:29.065+0800	ERROR	logsys/learn_more.go:192	#2 This is an ERROR message	{"root": "1st", "root": "2nd"}
2020-04-27T23:54:29.065+0800	DPANIC	logsys/learn_more.go:193	#2 This is a DPANIC message	{"root": "1st", "root": "2nd"}
2020-04-27T23:54:29.065+0800	ERROR	logsys/learn_more.go:199	#3 This is an ERROR message	{"root": "1st", "root": "2nd", "root": "3rd"}
2020-04-27T23:54:29.065+0800	DPANIC	logsys/learn_more.go:200	#3 This is a DPANIC message	{"root": "1st", "root": "2nd", "root": "3rd"}
```

Expected:
```log
2020-04-27T23:54:29.065+0800	DEBUG	logsys/learn_more.go:182	#1 This is a DEBUG message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	INFO	logsys/learn_more.go:183	#1 This is an INFO message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	WARN	logsys/learn_more.go:184	#1 This is a WARN message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	ERROR	logsys/learn_more.go:185	#1 This is an ERROR message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	DPANIC	logsys/learn_more.go:186	#1 This is a DPANIC message	{"root": "1st"}
2020-04-27T23:54:29.065+0800	INFO	logsys/learn_more.go:190	#2 This is an INFO message	{"root": "2nd"}
2020-04-27T23:54:29.065+0800	WARN	logsys/learn_more.go:191	#2 This is a WARN message	{"root": "2nd"}
2020-04-27T23:54:29.065+0800	ERROR	logsys/learn_more.go:192	#2 This is an ERROR message	{"root": "2nd"}
2020-04-27T23:54:29.065+0800	DPANIC	logsys/learn_more.go:193	#2 This is a DPANIC message	{"root": "2nd"}
2020-04-27T23:54:29.065+0800	ERROR	logsys/learn_more.go:199	#3 This is an ERROR message	{"root": "3rd"}
2020-04-27T23:54:29.065+0800	DPANIC	logsys/learn_more.go:200	#3 This is a DPANIC message	{"root": "3rd"}
```

**Comment by prashantv** [comment] 2020-04-27 16:02
Please see #622 for some more context, but this is working as intended. This behaviour is a little surprising, but to achieve high performance, zap holds a partially encoded JSON buffer as fields are added, rather than storing a reference to the field itself. It does not try to check or modify this JSON buffer, but only appends to the buffer, which keeps zap performant.

For what you are trying to do, consider using the [`Named`](https://pkg.go.dev/go.uber.org/zap?tab=doc#Logger.Named) option which appends the values passed in, so you would get something like `name: 1st.2nd.3rd`.'

Closing as a duplicate of #622 -- if you have any other questions, we can discuss them in the other issue.

**Closed by prashantv** 2020-04-27 16:02 UTC
