### ISSUE TITLE
expose Enabled in Logger interface

### ISSUE THREAD

**Issue by rogpeppe** [uber-go/zap#190] opened 2016-11-27 11:27 UTC
Currently, we have Logger.Check, which is useful if you want to
save code for a known logging message, but it's not so
great if you might guard a block of code that might log different
messages or multiple entries, because it makes an allocation
where none is needed.
 
So I wonder whether it might be nice to expose:

    // Enabled reports whether logging at the given level is enabled.
    Enabled(lvl Level) bool

**Comment by akshayjshah** [comment] 2016-11-29 05:35
Hey @rogpeppe - thanks for the interest in zap!

We used to expose `Enabled` on logger instances, but it proved inadequate when we added the sampling wrapper (which we use pretty widely). The problem is that we're not just interested in whether, e.g., `DebugLevel` is enabled, but whether the message in question will actually be logged. It's only worth allocating the slice of fields if *both* the level is enabled and the message won't be dropped.

We're planning to land a version of #191 shortly, which will pool checked messages; this should remove the allocation you're seeing.

What do you think of that? I'm not completely opposed to adding `Enabled` back to the logger interface, but I don't think that it's sufficient to guard a block of logging statements.

**Comment by lhecker** [comment] 2016-12-09 18:21
@akshayjshah In my case I need to register some logging-specific hooks for debug-level logs. It's IMHO cleanlier if we can ask the logging instance for it's current level directly instead of storing it elsewhere separately. I guess `Meta.Enabled` isn't going anywhere that soon anyways right? In that case adding this method back would IMHO be easy enough to warrant this change. 🙂

**Comment by jcorbin** [comment] 2016-12-09 18:29
On `Meta`, I'm currently working to drop it by wholly subsuming it into the unexported logger type. That said, the upcoming `zap.Facility` does expose an `Enabled` API. However we'll probably not be able to ask facility about its "current level". For more on this bleeding edge, see #201.

**Comment by akshayjshah** [comment] 2016-12-19 16:50
@lhecker What you've proposed is simple enough for the base logger; however, more complex loggers (like the sampling logger) present some difficulties. When we call `Enabled`, we need to increment an atomic to figure out whether the proposed message will actually be logged. When you call `Debug`, the same atomic will be incremented again, and your message may be dropped. This is clearly incorrect.

The checked message API avoids this issue. You should be able to use the `Check` API with `DebugLevel` and your proposed message, triggering your hook logic only if the checked message is `OK()`.

**Comment by akshayjshah** [comment] 2017-01-28 03:37
This is now possible on `dev`, since `Logger.Facility()` exposes the underlying `Facility`, which has an `Enabled` method.

**Closed by akshayjshah** 2017-01-28 03:37 UTC
Labels: enhancement
