### ISSUE TITLE
how to define my own `zap.Option` 

### ISSUE THREAD

**Issue by bestgopher** [uber-go/zap#823] opened 2020-04-28 09:39 UTC
Hi, how to define my own `zap.Option` and modify some `zap.Logger` fields in `Option.apply` method.

**Comment by abhinav** [comment] 2020-04-28 15:28
The `zap.Option` type is intentionally opaque to reduce the surface area of
the API.

What kind of option are you trying to define? What's the intended behavior?
It may be possible to build that out of the existing option constructors.

**Comment by bestgopher** [comment] 2020-04-29 00:51
Em...I want to change the properties of logger by specifying command line parameters.Maybe I can achieve this by returning different built-in `zap.Option` functions.Like this:
```
func myOptions() []zap.Option {

	var options []zap.Option
	if xxx {
		options = append(options, zap.WithCaller(true))
	}
	...
	return options

}

var logger = zap.NewExample(myOptions()...)
```

**Comment by abhinav** [comment] 2020-04-29 01:14
Yeah, that would be best. You can build up a list of options based on
the command line flags and then build a logger out of that. We do that
a fair bit as well, because our logger configuration is specified in
YAML.

Closing since the question was answered.

**Closed by abhinav** 2020-04-29 01:14 UTC
