### ISSUE TITLE
Can We Also Export Logs in Text Format.

### ISSUE THREAD

**Issue by DNadar** [uber-go/zap#86] opened 2016-06-25 10:08 UTC
Using Zap i see logs are generated in Json Format, which is actually good.

What if we want to log Messages in File in Text Format like 

 2014-07-23 16:19:53,897:DEBUG  :http-/0.0.0.0:28080-6:  This is Error Message
 2014-07-23 16:19:53,897:ERROR :http-/0.0.0.0:28080-6:  UnHandled Exception

Thanks,
DNadar

**Comment by akshayjshah** [comment] 2016-06-28 14:27
Yep! We're planning to add this before or shortly after a 1.0 release. This is a duplicate of #59, so I'm going to close it - follow the other issue for updates.

**Closed by akshayjshah** 2016-06-28 14:27 UTC
Labels: duplicate
