### ISSUE TITLE
How to change the _callerSkip while using the zap logger with AddCaller

### ISSUE THREAD

**Issue by arthurkiller** [uber-go/zap#216] opened 2016-12-21 12:48 UTC
Hey! We have re-packaged the zap log going with AddCaller,  and now the **_callerSkip** with 4 by default need to change to 8 to make a right caller information .How could we do this ?

Will this variable be exported? Then we can use this to change 
``` go
import "githb.com/zap"
...
zap.CallerSkip = 8
...
```
I have do this in PR  #215
 @akshayjshah @jcorbin 
Thx a lot

**Comment by arthurkiller** [comment] 2016-12-21 12:51
We are using not only zap in our projects. To give out an unique interface, we have to package the logs (include zap) together

**Comment by akshayjshah** [comment] 2016-12-21 15:37
Duplicate of #40.

**Closed by akshayjshah** 2016-12-21 15:37 UTC
